# Generated by Django 4.0.3 on 2022-03-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
